export const LABELS = {
	skipToContent: ['Skip to content', 60],
	homeLinkAria: ['home', 60],
	navigationPrimaryAria: ['Primary', 60],
	navigationMobileAria: ['Mobile', 60],
	menu: ['Menu', 30],
	resume: ['Resume ↗', 40],
	resumeNewTab: ['(opens PDF in new tab)', 80],
	newTab: ['(opens in new tab)', 80],
	availability: ['Available for work', 60],
	heroPrimaryCta: ['View case studies →', 60],
	heroSecondaryCta: ['Get in touch', 60],
	studies: ['studies', 30],
	projects: ['projects', 30],
	steps: ['steps', 30],
	exhibits: ['exhibits', 30],
	projectLink: ['View project →', 30],
	projectPending: ['Coming soon', 30],
	coverPending: ['Screenshot not cleared for sharing yet', 80],
	formName: ['Name', 60],
	formEmail: ['Email', 60],
	formPhone: ['Phone (optional)', 60],
	formReasonLabel: ['Reason (optional)', 60],
	formReasonPlaceholder: ['Choose a reason', 60],
	formMessage: ['Message', 60],
	honeypot: ['Do not fill this field', 80],
	submit: ['Send message →', 60],
	submitting: ['Sending…', 60],
	formErrorRequired: ['Enter your {field}.', 120],
	formErrorEmail: ['Enter a valid email address.', 120],
	formErrorSummary: ['Complete these {number} fields:', 120],
	formErrorSummaryOne: ['Complete this field:', 120],
	casesMore: ['Show all case studies ↓', 40],
	casesLess: ['Show fewer ↑', 40],
	skillsMore: ['Show all skills ↓', 40],
	skillsLess: ['Show fewer ↑', 40],
	contactSuccess: ['Thanks. I reply within two working days.', 200],
	contactAgain: ['Send another message', 60],
	draftRestored: ['Restored your unsent draft.', 120],
	draftDiscard: ['Discard', 40],
	draftDiscardConfirm: ['Discard for good?', 40],
	draftDiscarded: ['Draft discarded.', 60],
	draftInProgress: ['Saved in this browser.', 80],
	draftUndo: ['Undo', 40],
	contactAgainDone: ['Form cleared. Write a new message.', 60],
	formCount: ['{number} of {total} characters', 60],
	submitShortcutMac: ['or Cmd + Enter', 40],
	submitShortcutOther: ['or Ctrl + Enter', 40],
	sentBackToWork: ['← Back to the work', 60],
	contactFailure: ['A required field is empty or the email address is not valid.', 200],
	contactError: ['Something went wrong. Please email me directly.', 200],
	contactRateLimit: [
		'That is several messages in a row. Please try again in {minutes} minutes, or email me directly.',
		200
	],
	allCases: ['← All case studies', 60],
	caseStamp: ['Case study', 40],
	caseYear: ['Year', 30],
	casePrevious: ['Previous study', 40],
	caseNext: ['Next study', 40],
	figuresHeading: ['Figures', 60],
	figuresIntro: ['Screens, diagrams, and documents from the work.', 300],
	figurePrefix: ['Fig.', 20],
	figureUnsupported: ['Not supported in this browser', 80],
	figureFallback: ['Falls back to', 40],
	figureOklchFallback: ['static sRGB swatches', 80],
	figurePopoverFallback: ['static nested frames', 80],
	figureShuffleFallback: ['instant reorder', 80],
	figureContrastFallback: ['precomputed text colors', 80],
	figureWavesFallback: ['static wave layers', 80],
	figureOklchTitle: ['Live hue ramp', 60],
	figurePopoverTitle: ['Nested popovers', 60],
	figureShuffleTitle: ['Tile shuffle', 60],
	figureContrastTitle: ['Contrast flip', 60],
	figureWavesTitle: ['Layered waves', 60],
	figureHue: ['Hue', 30],
	figureShuffleAction: ['Shuffle', 30],
	figureShuffleOrder: ['New order: {order}', 60],
	figureShuffleCaption: ['Reordered with a view transition', 120],
	figureContrastCaption: ['Each label is contrast-color(tile)', 120],
	figureOklchCaption: ['Five lightness steps, one hue', 120],
	figureWavesCaption: ['Three timers, paused offscreen', 120],
	figureWavesPause: ['Pause', 30],
	figureWavesPlay: ['Play', 30],
	figurePopoverCaption: ['Each level opens inside the last', 120],
	figureMirrorDepth: ['Level {number} / {total}', 40],
	figureMirrorOpen: ['Open →', 30],
	figureMirrorAria: ['Open mirror, level {number} of {total}', 80],
	popoverOpen: ['Enlarge image', 60],
	popoverClose: ['Close', 30],
	popoverPrevious: ['Previous image', 40],
	popoverNext: ['Next image', 40],
	popoverPosition: ['{number} of {total}', 30],
	errorTitle: ['Page not found', 80],
	errorBody: ['That page has moved or never existed.', 200],
	errorServerTitle: ['Something went wrong', 80],
	errorServerBody: ['This page could not load. Please try again in a moment.', 200],
	errorHome: ['← Back home', 60],
	errorCases: ['Case studies', 60],
	errorExhibits: ['Exhibits', 60],
	errorContact: ['Get in touch', 60],
	// Must differ from navigationPrimaryAria: the header's navigation is on this page too.
	errorRoutesAria: ['Suggested pages', 60]
} as const satisfies Record<string, readonly [text: string, max: number]>

export type LabelKey = keyof typeof LABELS

export const DEFAULT_LABELS = Object.fromEntries(Object.entries(LABELS).map(([key, [text]]) => [key, text])) as Record<
	LabelKey,
	string
>
